### ISSUE TITLE
BouncyCastle Error

### ISSUE THREAD

**Issue by i542873057** [oracle/oci-dotnet-sdk#75]
Hi!

when i finish config in windows  and run in the first time .  it throw an error e.g:
`
System.InvalidCastException: Unable to cast object of type 'Org.BouncyCastle.Crypto.Parameters.RsaKeyParameters' to type 'Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters'.
   at Oci.Common.Auth.FilePrivateKeySupplier.ReadKey()
   at Oci.Common.Auth.FilePrivateKeySupplier.GetKey()
   at Oci.Common.Auth.SimpleAuthenticationDetailsProvider.GetPrivateKey()
   at Oci.Common.Auth.ConfigFileAuthenticationDetailsProvider.GetPrivateKey()
   at Oci.Common.Http.Signing.DefaultRequestSigner..ctor(IBasicAuthenticationDetailsProvider authDetailsProvider, SigningStrategy signingStrategy, ISigner signer)
   at Oci.Common.Http.Signing.DefaultRequestSigner..ctor(IBasicAuthenticationDetailsProvider authDetailsProvider, SigningStrategy signingStrategy)
   at Oci.Common.Http.Signing.DefaultRequestSigner..ctor(IBasicAuthenticationDetailsProvider authDetailsProvider)
   at Oci.Common.ClientBase..ctor(IBasicAuthenticationDetailsProvider authProvider, ClientConfiguration clientConfiguration)
   at Oci.Common.RegionalClientBase..ctor(IBasicAuthenticationDetailsProvider authProvider, ClientConfiguration clientConfiguration)
   at Oci.IdentityService.IdentityClient..ctor(IBasicAuthenticationDetailsProvider authenticationDetailsProvider, ClientConfiguration clientConfiguration, String endpoint)
`

**Comment by github-anurag** [comment]
Hi @i542873057 
What version of the Dotnet SDK are you using?

**Comment by i542873057** [comment]
> Hi @i542873057
> What version of the Dotnet SDK are you using?

Thank for your Reply

Version is 24.1.0
Installed by Nuget

**Comment by github-anurag** [comment]
@i542873057 
It looks the SDK does not like the pem file you are using here. Can you share the process you used to create yours?

Preferred way for creating Pem keys:-
https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm

**Comment by i542873057** [comment]
> @i542873057
> It looks the SDK does not like the pem file you are using here. Can you share the process you used to create yours?
> 
> Preferred way for creating Pem keys:-
> https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm

My os version is centos 8
This is my steps:
1.mkdir ~/.oci    
2.openssl genrsa -out ~/.oci/oci_api_key.pem 2048                  
3.openssl rsa -pubout -in ~/.oci/oci_api_key.pem -out ~/.oci/oci_api_key_public.pem             
4.move to console -->user setting---->api keys--->add api key   then upload the oci_api_key_public.pem，it will show me the config content, and i copy that in to my linux path ~/.oci/config ...
5.modify the  key_file params in config  "~/.oci/oci_api_key.pem"  

follow the Previous steps .  Then  i run my code  and throw the "BouncyCastle Error" you see at the begin

**Comment by github-anurag** [comment]
Hi @i542873057 
I cannot reproduce this on version 24.1.0 but we have this issue in older versions.
Can you again check the version of OCI.DotNetSDK.Common nuget package in your project?

```
$ dotnet list package
Project 'TestConsoleApp' has the following package references
   [net5.0]:
   Top-level Package                   Requested   Resolved
   > OCI.DotNetSDK.Common              24.1.0      24.1.0
   > OCI.DotNetSDK.Identity            24.1.0      24.1.0
   > OCI.DotNetSDK.ResourceSearch      24.1.0      24.1.0
```

**Comment by i542873057** [comment]
> @i542873057 looks like you are generating the API key locally yourself -- do you get the same issue if you generate the API key through the OCI Console, and use that key with the .NET SDK? See https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#two section 'Generating an API Signing Key (Console)' for how to do that.

Whoo~Thanks ! 
EveryThing is Ok when using the pem download from  console
