### ISSUE TITLE
OCI.DotNetSDK.IdentityDataPlane doesn't install all the required dependencies.

### ISSUE THREAD

**Issue by vikram055** [oracle/oci-dotnet-sdk#96]
I am using sample test case given here, 
https://docs.oracle.com/en-us/iaas/tools/dot-net-examples/29.4.0/identitydataplane/GenerateScopedAccessToken.cs.html, 
to get db token from IAM using OCI .NET SDK. 
I installed the latest **OCI.DotNetSDK.IdentityDataPlane (v. 29.4.0)** package from public nuget repository, https://www.nuget.org/packages/OCI.DotNetSDK.Identitydataplane/. 
But it doesn't install **BouncyCastle.NetCore package (v. 1.8.10)**, which is a required dependency, in order to run the test successfully. **Is this expected**?

If this is expected and it doesn't need to be installed, then, please could you let me know how can I resolve the following error.

GenerateScopedAccessToken Failed with Org.BouncyCastle.OpenSsl.PemException: problem creating ENCRYPTED private key: Org.BouncyCastle.Crypto.InvalidCipherTextException: pad block corrupted
   at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input) in /_/crypto/src/crypto/paddings/Pkcs7Padding.cs:line 69
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff) in /_/crypto/src/crypto/paddings/PaddedBufferedBlockCipher.cs:line 271
   at Org.BouncyCastle.Crypto.BufferedBlockCipher.DoFinal(Byte[] input, Int32 inOff, Int32 inLen) in /_/crypto/src/crypto/BufferedBlockCipher.cs:line 300
   at Org.BouncyCastle.Crypto.BufferedCipherBase.DoFinal(Byte[] input) in /_/crypto/src/crypto/BufferedCipherBase.cs:line 72
   at Org.BouncyCastle.Pkcs.PrivateKeyInfoFactory.CreatePrivateKeyInfo(Char[] passPhrase, Boolean wrongPkcs12Zero, EncryptedPrivateKeyInfo encInfo) in /_/crypto/src/pkcs/PrivateKeyInfoFactory.cs:line 270
   at Org.BouncyCastle.OpenSsl.PemReader.ReadPrivateKey(PemObject pemObject) in /_/crypto/src/openssl/PEMReader.cs:line 342
   at Org.BouncyCastle.OpenSsl.PemReader.ReadPrivateKey(PemObject pemObject) in /_/crypto/src/openssl/PEMReader.cs:line 367
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject() in /_/crypto/src/openssl/PEMReader.cs:line 97
   at Oci.Common.Auth.FilePrivateKeySupplier.ReadKey()
   at Oci.Common.Auth.FilePrivateKeySupplier.GetKey()
   at Oci.Common.Auth.SimpleAuthenticationDetailsProvider.GetPrivateKey()
   at Oci.Common.Auth.ConfigFileAuthenticationDetailsProvider.GetPrivateKey()
   at Oci.Common.Http.Signing.DefaultRequestSigner..ctor(IBasicAuthenticationDetailsProvider authDetailsProvider, SigningStrategy signingStrategy, ISigner signer)
   at Oci.Common.Http.Signing.DefaultRequestSigner..ctor(IBasicAuthenticationDetailsProvider authDetailsProvider, SigningStrategy signingStrategy)
   at Oci.Common.Http.Signing.DefaultRequestSigner..ctor(IBasicAuthenticationDetailsProvider authDetailsProvider)
   at Oci.Common.ClientBase..ctor(IBasicAuthenticationDetailsProvider authProvider, ClientConfiguration clientConfiguration)
   at Oci.Common.RegionalClientBase..ctor(IBasicAuthenticationDetailsProvider authProvider, ClientConfiguration clientConfiguration)
   at Oci.IdentitydataplaneService.DataplaneClient..ctor(IBasicAuthenticationDetailsProvider authenticationDetailsProvider, ClientConfiguration clientConfiguration, String endpoint)
   at iam_core.Program.GetDBToken() in C:\Users\vikrkuku\source\repos\iam_core\iam_core\Program.cs:line 161

**Comment by github-anurag** [comment]
@vikram055 
You will need to get the corresponding OCI.DotNetSDK.Common nuget package (The one with the same version as OCI.DotNetSDK.IdentityDataPlane) as well.

**Comment by github-anurag** [comment]
The Common package gets the BouncyCastle 3P dependency. Refer:-

```
09:44 $ dotnet list package --include-transitive
Project 'TestDotnetIAM' has the following package references
   [net5.0]:
   Top-level Package                      Requested   Resolved
   > OCI.DotNetSDK.Common                 29.4.0      29.4.0
   > OCI.DotNetSDK.IdentityDataPlane      29.4.0      29.4.0

   Transitive Package                           Resolved
   > Microsoft.CSharp                           4.7.0
   > Microsoft.IdentityModel.JsonWebTokens      6.7.1
   > Microsoft.IdentityModel.Logging            6.7.1
   > Microsoft.IdentityModel.Tokens             6.7.1
   > Newtonsoft.Json                            12.0.3
   > NLog                                       4.7.2
   > Polly                                      7.2.0
   > Portable.BouncyCastle                      1.8.6.7
   > System.ComponentModel.Annotations          4.7.0
   > System.IdentityModel.Tokens.Jwt            6.7.1
   > System.Security.Cryptography.Cng           4.5.0
```
Let me know if this answers your questions. If it does, then please close the issue. Thanks!
